const actionTypes = {
  LOGIN: "LOGIN",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGOUT: "LOGOUT",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",

  GET_POSTS: "GET_POSTS",
  GET_POSTS_LIMIT: "GET_POSTS_LIMIT",
  GET_NEW_POST: "GET_NEW_POST",
  EDIT_DATA: "EDIT_DATA",
  RESET_DATA_EDIT: "RESET_DATA_EDIT",
  GET_OUTSTANDING: "GET_OUTSTANDING",

  GET_CATEGORIES: "GET_CATEGORIES",
  GET_PRICES: "GET_PRICES",
  GET_AREAS: "GET_AREAS",
  GET_PROVINCES: "GET_PROVINCES",
  GET_POSTS_ADMIN: "GET_POSTS_ADMIN",
  // USER
  GET_CURRENT: "GET_CURRENT",
  GET_FAVORITES: "GET_FAVORITES",
  GET_FAVORITES_LIMIT: "GET_FAVORITES_LIMIT",
  ADD_FAVORITE: "ADD_FAVORITE",
  REMOVE_FAVORITE: "REMOVE_FAVORITE",
  GET_ALL_USERS: "GET_ALL_USERS",
  DELETE_USER: "DELETE_USER",
};

export default actionTypes;
